-- INSERT EN BBDD TABLA ROL
INSERT INTO rol (rolname) VALUES
("Admin"),
("User");


-- INSERT EN BBDD TABLA USER
INSERT INTO user (nickname, firstname, lastname, mail, password, rolid) VALUES
("ZhuN", "Ivan", "Casado", "ivan@casado.com", "$2a$10$DoRA8GOZSgFy5/hz1L8DleOEaV60/xa6QigGVcCoF8dAzXo/b0jdC", 1),
("Robus", "Paco", "Ortega Ruiz", "paco@ortega.es", "$2a$10$A.yUx3auG09VNtHAkfaxFeiVUpLRzXBRt3sf8MNpydNi1u.lmagHe", 2),
("Melk", "Luis", "Mariano Cobos", "luis@ortega.com", "$2a$10$ZpK/bl.F5UAgzOEBX0xVkOQ6bZKePifQEmz3eOCS6lrF/T0p88C3K", 2),
("Marco", "Marcos", "Vera Rodriguez", "marcos@vera.com", "$2a$10$hB3fzDEcDJbLOZ0ZLjq8OupvkG3dyhi3IHCJBJ4Fg/ebffLAHUFLG", 2);


-- INSERT EN BBDD TABLA MOVIES_CART
INSERT INTO movies_cart (cartid, userid) VALUES
(1, 2),
(2, 3),
(3, 4);


-- INSERT EN BBDD TABLA PURCHASE
INSERT INTO purchase (nickname, date, address1, location, zipcode, province, country, shipping_cost, total_cost) VALUES
("Robus", '2024-05-20 01:07:58.000000', "Avenida del Padre Esplá, nº 118", "Alicante", "03015", "Alicante", "España", 5, 25),
("Marco", '2024-05-21 11:14:08.000000', "Avenida Duquesa de la Victoria, num. 38", "Melilla", "52006", "Melilla", "España", 15, 62.75),
("Robus", '2024-06-09 07:02:05.000000', "Avenida del Padre Esplá, nº 118", "Alicante", "03015", "Alicante", "España", 0, 54),
("Robus", '2024-06-13 23:14:06.000000', "Avenida del Padre Esplá, nº 118", "Alicante", "03015", "Alicante", "España", 5, 9);


-- INSERT EN BBDD TABLA PURCHASE_ITEM
INSERT INTO purchase_item (purchase_id, purchase_itemid, title, quantity) VALUES
(1, 1, "El Rey León", 1),
(1, 2, "Kung Fu Panda 2", 1),
(2, 3, "Gladiator", 1),
(2, 4, "El Señor de los Anillos: La Comunidad del Anillo", 1),
(2, 5, "El Señor de los Anillos: Las dos torres", 1),
(2, 6, "El Señor de los Anillos: El retorno del Rey", 1),
(3, 7, "Los minions: nace un villano", 1),
(3, 8, "Los minions", 1),
(3, 9, "Avatar", 2),
(4, 10, "Aladdin", 1);


-- INSERT EN BBDD TABLA ADDRESS
INSERT INTO address (userid, addressid, address_line1, location, zipcode, province, country) VALUES
(2, 1, "Avenida del Padre Esplá, nº 118", "Alicante", "03015", "Alicante", "España"),
(3, 2, "Avenida de la Condomina, nº 253", "Alicante", "03012", "Alicante", "España");


-- INSERT EN BBDD TABLA ADDRESS
INSERT INTO address (userid, addressid, address_line1, address_line2, location, zipcode, province, country) VALUES
(4, 3, "Avenida Duquesa de la Victoria, num. 38", "Torre C, 2º A", "Melilla", "52006", "Melilla", "España");


-- INSERT EN BBDD TABLA CATALOGUE
INSERT INTO catalogue (title, description, release_date, genre, director, new_release, stock, price, img_url) VALUES 
("Dune", "El desértico planeta Arrakis, queda en manos de la Casa de los Atreides por orden del emperador. El duque Leto, la dama Jessica y el hijo de ambos, Paul Atreides, llegan a Arrakis con la esperanza de mantener el buen nombre de su casa y ser fieles al emperador, pero pronto se verán envueltos en una trama que les llevará a valorar a los lugareños, los Fremen, una estirpe de habitantes del desierto con una estrecha relación con la especia.", "22-10-2021", "Fantasy", "Denis Villeneuve", true, 50, 10, "images/frontMovies/dune.jpg"),
("Uncharted", "Uncharted presenta a un joven, astuto y carismático, Nathan Drake (Tom Holland) en su primera aventura como cazatesoros con su ingenioso compañero Victor “Sully” Sullivan. En una aventura de acción que se extiende por todo el mundo, ambos se embarcan en una peligrosa búsqueda de “el mayor tesoro nunca antes encontrado” al tiempo que rastrean las claves que les podrían conducir al hermano de Nathan, perdido hace ya mucho tiempo.", "18-02-2022", "Adventures", "Ruben Fleischer", true, 8, 15, "images/frontMovies/uncharted.jpg"),
("El Padrino", "El Padrino es una película de gángsters dirigida por Francis Ford Coppola que se estrenó en 1972. Está basada en la novela del mismo nombre de Mario Puzo y sigue la historia de la familia mafiosa Corleone, centrándose en el ascenso al poder de Michael Corleone, interpretado por Al Pacino.", "24-03-1972", "Crime", "Francis Ford Coppola", false, 30, 10, "images/frontMovies/elpadrino.jpg"),
("Titanic", "Titanic es una epopeya romántica dirigida por James Cameron que se estrenó en 1997. La película está protagonizada por Leonardo DiCaprio y Kate Winslet y cuenta la historia de amor entre Jack y Rose, dos pasajeros a bordo del famoso transatlántico que se hunde en su viaje inaugural.", "18-12-1997", "Romance", "James Cameron", false, 100, 12, "images/frontMovies/titanic.jpg"),
("El Señor de los Anillos: La Comunidad del Anillo", "El Señor de los Anillos: La Comunidad del Anillo es la primera entrega de la trilogía épica dirigida por Peter Jackson, basada en la obra de J.R.R. Tolkien. La película sigue la búsqueda del Anillo Único por parte del hobbit Frodo Bolsón y su compañía, mientras intentan destruirlo para evitar que caiga en manos del Señor Oscuro Sauron.", "19-12-2001", "Fantasy", "Peter Jackson", false, 76, 15, "images/frontMovies/elsenordelosanillos1.jpg"),
("Harry Potter y la Piedra Filosofal", "Harry Potter y la Piedra Filosofal es la primera película de la franquicia basada en los libros de J.K. Rowling. Dirigida por Chris Columbus, la película sigue a Harry Potter, un niño que descubre que es un mago y comienza su educación en la escuela de magia y hechicería de Hogwarts.", "16-11-2001", "Fantasy", "Chris Columbus", false, 22, 15, "images/frontMovies/harrypotter1.jpg"),
("Jurassic Park", "Jurassic Park es una película de ciencia ficción dirigida por Steven Spielberg que se estrenó en 1993. Basada en la novela de Michael Crichton, la película sigue a un grupo de científicos y aventureros que visitan un parque temático poblado por dinosaurios clonados.", "11-06-1993", "ScienceFiction", "Steven Spielberg", false, 4, 12, "images/frontMovies/jurassicpark1.jpg"),
("Avatar", "Avatar es una película de ciencia ficción épica dirigida por James Cameron que se estrenó en 2009. La película está ambientada en el año 2154, donde los humanos están explorando Pandora, un exuberante satélite habitado por la raza Na'vi, con el fin de extraer un mineral valioso. La historia sigue a Jake Sully, un exmarine parapléjico que se embarca en una misión para ganar la confianza de los Na'vi y proteger su hogar de la explotación humana.", "18-12-2009", "ScienceFiction", "James Cameron", false, 20, 15, "images/frontMovies/avatar1.jpg"),
("Los Increíbles", "Los Increíbles es una película de animación de superhéroes dirigida por Brad Bird y producida por Pixar Animation Studios. La historia sigue a una familia de superhéroes retirados que son obligados a volver a la acción para salvar al mundo. La película combina elementos de comedia, acción y aventura.", "05-11-2004", "Animation", "Brad Bird", false, 11, 10, "images/frontMovies/losincreibles.jpg"),
("Interestelar", "Interestelar es una película de ciencia ficción dirigida por Christopher Nolan que se estrenó en 2014. La película sigue a un grupo de astronautas que viajan a través de un agujero de gusano en busca de un nuevo hogar para la humanidad, ya que la Tierra se enfrenta a una crisis ambiental.", "07-11-2014", "ScienceFiction", "Christopher Nolan", false, 42, 12, "images/frontMovies/interestelar.jpg"),
("El Rey León", "El Rey León es una película animada de Disney dirigida por Roger Allers y Rob Minkoff, estrenada en 1994. La película sigue la historia de Simba, un joven león que debe enfrentar su destino como rey después de la muerte de su padre, Mufasa.", "24-06-1994", "Animation", "Roger Allers, Rob Minkoff", false, 66, 10, "images/frontMovies/elreyleon.jpg"),
("El Caballero Oscuro", "El Caballero de la Noche es una película de superhéroes dirigida por Christopher Nolan que se estrenó en 2008. La película es la secuela de Batman Begins y sigue al héroe de Gotham, Batman, mientras se enfrenta al caos desatado por el Joker.", "18-07-2008", "Action", "Christopher Nolan", false, 80, 12, "images/frontMovies/elcaballerooscuro.jpg"),
("La La Land", "La La Land es un musical romántico dirigido por Damien Chazelle que se estrenó en 2016. La película sigue a Mia, una aspirante a actriz, y a Sebastian, un pianista de jazz, mientras persiguen sus sueños en Los Ángeles y navegan por su relación.", "09-12-2016", "Musical", "Damien Chazelle", false, 6, 9, "images/frontMovies/lalaland.jpg"),
("Toy Story", "Toy Story es una película de animación dirigida por John Lasseter y producida por Pixar Animation Studios, estrenada en 1995. La película sigue a un grupo de juguetes que cobran vida cuando sus dueños no están presentes, centrándose en la relación entre Woody, un vaquero de juguete, y Buzz Lightyear, un juguete espacial.", "22-11-1995", "Animation", "John Lasseter", false, 0, 8, "images/frontMovies/toystory.jpg"),
("La forma del agua", "La forma del agua es una película de fantasía romántica dirigida por Guillermo del Toro que se estrenó en 2017. La película sigue la relación entre Elisa, una mujer muda que trabaja como limpiadora en un laboratorio gubernamental, y un misterioso hombre anfibio que está siendo retenido en el laboratorio.", "08-12-2017", "Fantasy", "Guillermo del Toro", false, 27, 10, "images/frontMovies/laformadelagua.jpg"),
("Matrix", "Matrix es una película de ciencia ficción dirigida por Lana y Lilly Wachowski que se estrenó en 1999. La película sigue a Neo, un hacker que descubre que el mundo en el que vive es una simulación controlada por máquinas inteligentes, y se une a la resistencia humana para luchar contra ellas.", "31-03-1999", "ScienceFiction", "Lana Wachowski, Lilly Wachowski", false, 19, 15, "images/frontMovies/matrix.jpg"),
("Forrest Gump", "Forrest Gump es una película de drama dirigida por Robert Zemeckis que se estrenó en 1994. La película sigue la vida de Forrest Gump, un hombre con discapacidad intelectual que se convierte en parte de varios eventos importantes de la historia estadounidense.", "06-07-1994", "Drama", "Robert Zemeckis", false, 41, 12, "images/frontMovies/forrestgump.jpg"),
("Shrek", "Shrek es una película animada dirigida por Andrew Adamson y Vicky Jenson que se estrenó en 2001. La película sigue las aventuras de Shrek, un ogro malhumorado que se embarca en una misión para rescatar a la princesa Fiona y reclamar su pantano de los personajes de cuentos de hadas.", "18-05-2001", "Animation", "Andrew Adamson, Vicky Jenson", false, 59, 12, "images/frontMovies/shrek.jpg"),
("Terminator 2: El juicio final", "Terminator 2: El juicio final es una película de ciencia ficción dirigida por James Cameron que se estrenó en 1991. La película sigue a Sarah Connor y a su hijo John mientras son perseguidos por un avanzado cyborg, el Terminator, enviado desde el futuro para asesinar a John Connor.", "03-07-1991", "ScienceFiction", "James Cameron", false, 122, 10, "images/frontMovies/terminator2.jpg"),
("El club de la lucha", "El club de la lucha es una película de drama dirigida por David Fincher que se estrenó en 1999. La película sigue a un insomne y un vendedor de jabón desilusionado que forman un club de lucha clandestino como forma de terapia de grupo, pero pronto se ven envueltos en algo mucho más oscuro.", "15-10-1999", "Drama", "David Fincher", false, 77, 10, "images/frontMovies/elclubdelalucha.jpg"),
("Regreso al Futuro", "Regreso al Futuro es una película de ciencia ficción dirigida por Robert Zemeckis que se estrenó en 1985. La película sigue a Marty McFly, un adolescente que accidentalmente viaja en el tiempo a 1955 y debe asegurarse de que sus padres se enamoren para salvar su propia existencia.", "03-07-1985", "ScienceFiction", "Robert Zemeckis", false, 22, 9, "images/frontMovies/regresoalfuturo.jpg"),
("El Pianista", "El Pianista es un drama biográfico dirigido por Roman Polanski que se estrenó en 2002. La película está basada en las memorias del pianista polaco de origen judío Władysław Szpilman, quien sobrevivió al Holocausto en Varsovia.", "24-05-2002", "Drama", "Roman Polanski", false, 18, 8, "images/frontMovies/elpianista.jpg"),
("Parásitos", "Parásitos es una película surcoreana dirigida por Bong Joon-ho que se estrenó en 2019. La película sigue a una familia pobre que se infiltra en la vida de una adinerada familia como empleados domésticos, desencadenando una serie de eventos inesperados.", "21-05-2019", "Drama", "Bong Joon-ho", true, 91, 12, "images/frontMovies/parasitos.jpg"),
("Bohemian Rhapsody", "Bohemian Rhapsody es un biopic musical dirigido por Bryan Singer y Dexter Fletcher que se estrenó en 2018. La película sigue la historia de Freddie Mercury y la banda Queen, desde sus inicios hasta su legendario concierto en el Live Aid de 1985.", "02-11-2018", "Musical", "Bryan Singer, Dexter Fletcher", false, 3, 8, "images/frontMovies/bohemianRhapsody.jpg"),
("El Gran Hotel Budapest", "El Gran Hotel Budapest es una comedia dramática dirigida por Wes Anderson que se estrenó en 2014. La película sigue las extravagantes aventuras de Gustave H, el legendario conserje de un famoso hotel europeo, y Zero Moustafa, un joven empleado que se convierte en su amigo más leal.", "06-03-2014", "Comedy", "Wes Anderson", false, 31, 9, "images/frontMovies/elgranhotelbudapest.jpg"),
("Gladiator", "Gladiator es una película épica dirigida por Ridley Scott que se estrenó en 2000. La película sigue la historia de Maximus Decimus Meridius, un general romano que es traicionado y convertido en esclavo, y que busca venganza en el coliseo romano como gladiador.", "05-05-2000", "Action", "Ridley Scott", false, 52, 15, "images/frontMovies/gladiador.jpg"),
("El Resplandor", "El Resplandor es una película de terror psicológico dirigida por Stanley Kubrick que se estrenó en 1980. Basada en la novela de Stephen King, la película sigue a Jack Torrance, un escritor y cuidador de un hotel, mientras se enfrenta a la creciente influencia maligna del lugar.", "13-06-1980", "Horror", "Stanley Kubrick", false, 17, 9, "images/frontMovies/elresplandor.jpg"),
("Coco", "Coco es una película de animación de Pixar dirigida por Lee Unkrich y Adrian Molina, estrenada en 2017. La película sigue a Miguel, un niño mexicano que sueña con ser músico, mientras viaja al mundo de los muertos y descubre los secretos de su familia.", "20-10-2017", "Animation", "Lee Unkrich, Adrian Molina", false, 29, 12, "images/frontMovies/coco.jpg"),
("El lobo de Wall Street", "El lobo de Wall Street es una comedia negra dirigida por Martin Scorsese que se estrenó en 2013. La película está basada en las memorias de Jordan Belfort y sigue su ascenso y caída como un corredor de bolsa de Wall Street.", "25-12-2013", "Comedy", "Martin Scorsese", false, 76, 12, "images/frontMovies/ellobodewallstreet.jpg"),
("Origen", "Mediante el uso de la tecnología de compartir sueños, un ladrón se dedica a robar secretos corporativos, hasta que se le encomienda la tarea de implantar una idea en la mente de un jefe de una gran empresa.", "09-07-2010", "ScienceFiction", "Christopher Nolan", false, 21, 12, "images/frontMovies/origen.jpg"),
("El Exorcista", "El Exorcista es una película de terror dirigida por William Friedkin que se estrenó en 1973. Basada en la novela de William Peter Blatty, la película sigue a dos sacerdotes que intentan exorcizar a una joven poseída por una entidad demoníaca.", "26-12-1973", "Horror", "William Friedkin", false, 24, 10, "images/frontMovies/elexorcista.jpg"),
("El Señor de los Anillos: Las dos torres", "Sam y Frodo se adentran en la tierra media dirección a Mordor guiados por Gollum, la comunidad del anillo divida se enfrenta a Saruman, el nuevo aliado de Sauron.", "18-12-2002", "Fantasy", "Peter Jackson", false, 98, 12, "images/frontMovies/elsenordelosanillos2.jpg"),
("El Señor de los Anillos: El retorno del Rey", "Última entrega del viaje de la Comunidad del Anillo para salvar la Tierra Media de la oscuridad impuesta por el malvado Sauron.", "17-12-2003", "Fantasy", "Peter Jackson", false, 114, 12, "images/frontMovies/elsenordelosanillos3.jpg"),
("Matrix Reloaded", "El ejército de las máquinas se dirige a la última ciudad de la humanidad, Sion. Neo, Morfeo y Trinity disponen de 72 horas antes de que las máquinas alcancen el santuario humano", "09-05-2003", "Action", "hermanas Wachowski", false, 33, 12, "images/frontMovies/matrix2.jpg"),
("Matrix Revolutions", "Neo en busca de la verdad ha quedado a la deriva en una tierra de nadie entre Matrix y el Mundo de las Máquinas. Morfeo se enfrenta a la revelación de que el Elegido, no es más que otro sistema de control inventado por los arquitectos de Matrix", "05-11-2003", "Action", "hermanas Wachowski", false, 45, 12, "images/frontMovies/matrix3.jpg"),
("Matrix Resurrections", "Neo, quien vive una vida aparentemente ordinaria bajo su identidad original como Thomas A. Anderson, pero cuando una nueva versión de Morfeo le ofrece la píldora roja y reabre su mente al mundo de Matrix. Neo se une a un grupo de rebeldes para luchar contra un nuevo enemigo", "22-12-2021", "Action", "Lana Wachowski", true, 18, 15, "images/frontMovies/matrix4.jpg"),
("El hobbit: un viaje inesperado", "Bilbo, un hobbit que vive una vida tranquila hasta que el mago Gandalf le encomienda una misión: unirse a un grupo de enanos para recuperar un tesoro que les pertenece, pero, el tesoro esta guardado por un dragón, Smaug. En su camino deberán enfrentarse a orcos y otros peligros, y un anillo de oro que tiene un poder extraordinario", "28-11-2012", "Fantasy", "Peter Jackson", false, 91, 12, "images/frontMovies/elhobbit1.jpg"),
("El hobbit: la desolación de Smaug", "Bilbo y sus compañeros continúan su viaje hacia el este y enfrentan muchos peligros de camino a la Montaña Solitaria, donde les aguarda el temible dragón Smaug", "13-12-2013", "Fantasy", "Peter Jackson", false, 31, 12, "images/frontMovies/elhobbit2.jpg"),
("El hobbit: La batalla de los cinco ejércitos", "Épico final de las aventuras de Bilbo Bolsón, Thorin Escudo de Roble y la Compañía de los Enanos. Después de reclamar su patria al dragón Smaug, se desató sin querer una fuerza malvada en el mundo. Furioso, Smaug descarga llamaradas de ira sobre los habitantes indefensos de Ciudad del Lago", "16-12-2014", "Fantasy", "Peter Jackson", false, 71, 12, "images/frontMovies/elhobbit3.jpg"),
("Seven", "Dos detectives, uno veterano y el otro novato, están desesperadamente en busca de un asesino en serie cuyos crímenes se basan en los siete pecados capitales", "22-09-1995", "Thriller", "David Fincher", false, 21, 9, "images/frontMovies/seven.jpg"),
("La Milla Verde", "En un corredor de la muerte en una prisión del sur durante la Gran Depresión, un guardia de la prisión tiene un encuentro sobrenatural con un hombre acusado de asesinato que posee un don misterioso", "10-12-1999", "Drama", "Frank Darabont", false, 39, 10, "images/frontMovies/lamillaverde.jpg"),
("Shutter Island", "En 1954, un U.S. Marshal investiga la desaparición de una asesina que escapó de un hospital para criminales dementes situado en una isla, pero descubre secretos que lo llevan a cuestionar su propia realidad", "19-02-2010", "Thriller", "Martin Scorsese", false, 21, 9, "images/frontMovies/shutterisland.jpg"),
("La lista de Schindler", "Un empresario alemán salva a más de mil judíos polacos de ser gaseados en el campo de concentración de Auschwitz durante la Segunda Guerra Mundial al emplearlos en su fábrica", "15-12-1993", "Drama", "Steven Spielberg", false, 18, 8, "images/frontMovies/lalistadeschindler.jpg"),
("Cadena perpetua", "Un banquero exitoso es condenado a cadena perpetua en la prisión estatal de Shawshank por los crímenes de su esposa y su amante, y encuentra consuelo y eventual redención a través de actos de decencia común", "23-09-1994", "Drama", "Frank Darabont", false, 41, 9, "images/frontMovies/cadenaperpetua.jpg"),
("Joker", "En Gotham City, el comediante fracasado Arthur Fleck se encuentra aislado y despreciado por la sociedad. Luego de una serie de trágicos eventos, Fleck comienza su descenso hacia la locura mientras se transforma en el criminal maestro conocido como Joker", "04-10-2019", "Thriller", "Todd Phillips", false, 23, 12, "images/frontMovies/joker.jpg"),
("Oppenheimer", "Crónica de J. Robert Oppenheimer, el físico teórico que lideró el Laboratorio Los Álamos del Proyecto Manhattan, el esfuerzo clandestino durante la Segunda Guerra Mundial para desarrollar la primera bomba atómica", "21-07-2023", "Drama", "Christopher Nolan", true, 73, 15, "images/frontMovies/oppenheimer.jpg"),
("Intocable", "Después de quedar parapléjico por un accidente de parapente, un aristócrata contrata a un joven de los suburbios para que sea su cuidador, resultando en una amistad poco probable pero firme", "02-12-2011", "Comedy", "Olivier Nakache, Éric Toledano", false, 63, 10, "images/frontMovies/intocable.jpg"),
("Alien: el octavo pasajero", "La tripulación de la nave espacial Nostromo es despertada de su sueño criogénico para investigar una llamada de auxilio de un planeta desolado, encontrándose con una amenaza mortal desconocida", "25-05-1979", "ScienceFiction", "Ridley Scott", false, 54, 10, "images/frontMovies/alieneloctavopasajero.jpg"),
("Alien: el regreso", "Ellen Ripley es rescatada por una estación espacial después de dormir en estasis durante 57 años. Su historia sobre el Alien es recibida con escepticismo, hasta que la comunicación se pierde con la colonia de exomoon donde se encontraron los Alien", "18-07-1986", "ScienceFiction", "James Cameron", false, 55, 9, "images/frontMovies/alien2.jpg"),
("Alien 3", "Ripley se estrella en un planeta prisión de máxima seguridad, descubriendo que había un alien a bordo de su nave. Ahora debe luchar contra la criatura mientras también se enfrenta a una comunidad de prisioneros", "22-05-1992", "Horror", "David Fincher", false, 28, 9, "images/frontMovies/alien3.jpg"),
("Alien: Resurrección", "200 años después de su muerte, Ripley es revivida como un poderoso híbrido humano/alien. Junto con una tripulación de contrabandistas, debe evitar que la criatura caiga en manos equivocadas", "26-11-1997", "ScienceFiction", "Jean-Pierre Jeunet", false, 34, 9, "images/frontMovies/alien4.jpg"),
("Alien vs. Predator", "Una pirámide antigua es descubierta en la Antártida, atrayendo a un equipo de científicos y aventureros al sitio. Pronto se encuentran atrapados en una batalla entre dos especies extraterrestres legendarias", "13-08-2004", "ScienceFiction", "Paul W.S. Anderson", false, 18, 8, "images/frontMovies/alienvspredator.jpg"),
("Aliens vs. Predator 2", "Después de que un enfrentamiento entre un Predator y un Alien cause estragos en una pequeña ciudad de Colorado, los residentes deben unirse para sobrevivir al mortal encuentro", "25-12-2007", "Horror", "Colin y Greg Strause", false, 22, 8, "images/frontMovies/alienvspredator2.jpg"),
("Prometheus", "Un equipo de exploradores descubre una pista sobre el origen de la humanidad en la Tierra, llevándolos a un viaje a los rincones más oscuros del universo. Allí, deben luchar por un futuro aterrador que podría significar el fin de la humanidad", "08-06-2012", "ScienceFiction", "Ridley Scott", false, 26, 10, "images/frontMovies/prometheus.jpg"),
("Alien: Covenant", "La tripulación de la nave colonia Covenant, en busca de un nuevo hogar para la humanidad, descubre un planeta que parece un paraíso inexplorado. Sin embargo, alberga un mundo oscuro y peligroso y su único habitante es el 'sintético' sobreviviente del condenado viaje de la Prometheus", "19-05-2017", "Horror", "Ridley Scott", false, 92, 12, "images/frontMovies/aliencovenant.jpg"),
("Alien Romulus", "Descripción genérica basada en los estándares de la saga Alien - Un equipo de investigación se encuentra con una nueva forma de vida extraterrestre en el lejano planeta Romulus, desencadenando una lucha por la supervivencia contra horrores desconocidos", "18-07-2024", "ScienceFiction", "Ridley Scot", false, 61, 15, "images/frontMovies/alienromulus.jpg"),
("La guerra de las galaxias", "Luke Skywalker se une a la Alianza Rebelde para ayudar a derrotar al Imperio Galáctico y a su malvado líder, el Emperador. En su viaje, Luke recibe la ayuda de amigos como Han Solo, la princesa Leia, y el sabio Obi-Wan Kenobi", "25-05-1977", "Adventures", "George Lucas", false, 41, 10, "images/frontMovies/laguerradelasgalaxias.jpg"),
("El imperio contraataca", "Después del exitoso ataque rebelde contra la Estrella de la Muerte, el Imperio lanza una despiadada persecución contra los miembros de la Alianza Rebelde, forzando a Luke Skywalker a comenzar su entrenamiento Jedi con Yoda", "21-05-1980", "Adventures", "Irvin Kershner", false, 46, 10, "images/frontMovies/elimperiocontraataca.jpg"),
("El retorno del Jedi", "En la conclusión épica de la saga, la Alianza Rebelde lanza una última ofensiva contra el Imperio Galáctico, mientras Luke Skywalker enfrenta a Darth Vader en una confrontación final para decidir el destino de la galaxia", "25-05-1983", "Adventures", "Richard Marquand", false, 51, 10, "images/frontMovies/elretornodeljedi.jpg"),
("La amenaza fantasma", "La República Galáctica se encuentra en un periodo de crisis. El Jedi Qui-Gon Jinn y su aprendiz Obi-Wan Kenobi son enviados a negociar con la Federación de Comercio, lo que los lleva a conocer al joven Anakin Skywalker, quien es sensible a la Fuerza", "19-05-1999", "Adventures", "George Lucas", false, 113, 10, "images/frontMovies/laamenazafantasma.jpg"),
("El ataque de los clones", "Diez años después de la 'Amenaza Fantasma', la galaxia está al borde de la guerra civil, con miles de sistemas solares amenazando con separarse de la República Galáctica. Bajo esta tensión, Anakin Skywalker y Padmé Amidala forman una conexión, mientras Obi-Wan Kenobi investiga un intento de asesinato sobre Padmé", "16-05-2002", "ScienceFiction", "George Lucas", false, 56, 10, "images/frontMovies/elataquedelosclones.jpg"),
("La venganza de los Sith", "Las Guerras Clon están llegando a su fin. El Canciller Palpatine ha sido secuestrado y Anakin Skywalker, ahora un Jedi Caballero, lidera una misión desesperada para rescatarlo. A medida que la Orden Jedi es destruida, Anakin es seducido por el lado oscuro de la Fuerza, convirtiéndose en Darth Vader", "19-05-2005", "ScienceFiction", "George Lucas", false, 65, 10, "images/frontMovies/lavenganzadelossith.jpg"),
("El despertar de la fuerza", "Tres décadas después de la victoria sobre el Imperio Galáctico, una nueva amenaza surge. La Primera Orden intenta gobernar la galaxia y solo un grupo de héroes puede detenerla, junto con la ayuda de la Resistencia", "18-12-2015", "ScienceFiction", "J.J. Abrams", false, 47, 10, "images/frontMovies/eldespertardelafuerza.jpg"),
("Los últimos Jedi", "La saga de Skywalker continúa cuando los héroes de 'El Despertar de la Fuerza' se unen a las leyendas galácticas en una aventura épica que desbloquea misterios de la Fuerza y revelaciones del pasado", "15-12-2017", "Adventures", "Rian Johnson", false, 58, 9, "images/frontMovies/losultimosjedi.jpg"),
("El ascenso de Skywalker", "La Resistencia sobreviviente enfrenta a la Primera Orden una vez más en el capítulo final de la saga Skywalker, donde se revelarán antiguos misterios de la Fuerza y se desvelará la batalla final por la libertad", "20-12-2019", "Adventures", "J.J. Abrams", false, 62, 10, "images/frontMovies/elascensodeskywalker.jpg"),
("Kung Fu Panda", "El oso panda Po se convierte en el improbable héroe cuando es elegido como el Guerrero Dragón para luchar contra el vil Tai Lung. Con la ayuda de los Cinco Furiosos, Po debe entrenar en kung fu y aprovechar el poder del Chi para salvar el Valle de la Paz", "06-06-2008", "Adventures", "Mark Osborne, John Stevenson", false, 32, 10, "images/frontMovies/kungfupanda.jpg"),
("Kung Fu Panda 2", "Po y los Cinco Furiosos descubren que el pavo real Lord Shen planea usar un arma secreta invencible para conquistar China y destruir el kung fu. Po debe buscar en su pasado y desbloquear los secretos de su misterioso origen para encontrar la fuerza que necesita para triunfar", "26-05-2011", "Animation", "Jennifer Yuh Nelson", false, 36, 10, "images/frontMovies/kungfupanda2.jpg"),
("Kung Fu Panda 3", "Cuando el padre biológico de Po reaparece, el dúo se reúne y viaja a un paraíso secreto de pandas donde conocen a un montón de nuevos y divertidos personajes. Pero cuando el sobrenatural villano Kai comienza a barrer China derrotando a todos los maestros de kung fu, Po debe hacer lo imposible: entrenar a un pueblo lleno de sus hermanos torpes para convertirse en el último equipo de Kung Fu Pandas", "29-01-2016", "Kids", "Jennifer Yuh Nelson, Alessandro Carloni", false, 61, 10, "images/frontMovies/kungfupanda3.jpg"),
("Aladdin", "Un joven callejero llamado Aladdin se embarca en una mágica aventura después de encontrar una lámpara que libera a un genio capaz de concederle tres deseos. Mientras tanto, el malvado hechicero Jafar tiene planes propios para la lámpara y para el futuro de Agrabah", "24-05-2019", "Kids", "Guy Ritchie", false, 135, 9, "images/frontMovies/aladdin.jpg"),
("Los minions", "Los Minions, las pequeñas criaturas amarillas, buscan desesperadamente un nuevo malvado maestro a quien servir y terminan en una convención de villanos donde compiten por el derecho a ser secuaces del malvado Scarlet Overkill", "10-07-2015", "Animation", "Kyle Balda, Pierre Coffin", false, 1, 12, "images/frontMovies/losminions.jpg"),
("Los minions 2: nace un villano", "En la década de 1970, los Minions buscan un nuevo villano al que servir y se encuentran con el joven Gru, embarcándose en una nueva aventura que establece la historia de cómo los Minions se convirtieron en sus seguidores leales", "01-07-2022", "Animation", "Kyle Balda, Brad Ableson", true, 83, 12, "images/frontMovies/minions2.jpg"),
("Gru 3: Mi villano favorito", "Gru se encuentra en una nueva misión con la ayuda de sus leales Minions, enfrentándose a nuevos desafíos y villanos mientras descubre el valor de la familia, la amistad y cómo ser un verdadero villano", "30-06-2017", "Adventures", "Pierre Coffin, Kyle Balda", false, 51, 10, "images/frontMovies/gru3.jpg"),
("Cars", "Rayo McQueen, un auto de carreras novato y arrogante, termina en un pequeño pueblo de la Ruta 66 en el camino hacia su mayor carrera. Allí, aprende valiosas lecciones sobre la amistad y la vida del ecléctico grupo de autos que conoce", "09-06-2006", "Animation", "John Lasseter", false, 40, 9, "images/frontMovies/cars.jpg"),
("Cars 2", "Rayo McQueen y su amigo Mate viajan al extranjero para competir en el primer Campeonato Mundial que determinará el auto más rápido del mundo. Sin embargo, la carrera se complica con una intrincada trama de espionaje internacional", "24-06-2011", "Animation", "John Lasseter, Brad Lewis", false, 9, 8, "images/frontMovies/cars2.jpg"),
("Leyendas de pasión", "Tres hermanos, criados en un rancho en Montana, se ven afectados por la historia, la guerra y el amor, rompiendo sus lazos familiares pero dejando atrás un legado de honor y pasión hacia la tierra y entre sí", "16-12-1994", "Romance", "Edward Zwick", false, 24, 12, "images/frontMovies/leyendasdepasion.jpg"),
("Vaiana", "Una joven audaz se embarca en una misión audaz para salvar a su pueblo. Durante su viaje, Moana conoce al otrora poderoso semidiós Maui, juntos cruzan el océano en un viaje lleno de acción, enfrentándose a monstruos feroces y obstáculos imposibles", "23-11-2016", "Animation", "Ron Clements, John Musker", true, 64, 12, "images/frontMovies/vaiana.jpg"),
("Iron Man", "Tony Stark, un industrial multimillonario y genio inventor, es secuestrado y obligado a construir un arma devastadora. En cambio, usa su inteligencia para construir un traje blindado poderoso y escapar. Al regresar a casa, Stark perfecciona el traje y lo usa para combatir el mal como Iron Man", "02-05-2008", "Action", "Jon Favreau", false, 31, 10, "images/frontMovies/ironman.jpg"),
("Mad Max: Furia en la carretera", "En un desierto post-apocalíptico, Max se une a Furiosa, una mujer que intenta llegar a su lugar de origen, mientras huyen de un señor de la guerra y sus secuaces en una brutal persecución en vehículos", "15-05-2015", "Action", "George Miller", false, 27, 9, "images/frontMovies/madmax.jpg"),
("Tiburón", "Un enorme tiburón blanco aterroriza a los habitantes y visitantes de Amity Island, llevando al jefe de policía local, un científico marino y un rudo cazador de tiburones a embarcarse en una desesperada misión para detenerlo", "20-06-1975", "Thriller", "Steven Spielberg", false, 51, 8, "images/frontMovies/tiburon.jpg"),
("Déjame salir", "Un joven afroamericano visita a la familia de su novia blanca, donde descubre la inquietante razón detrás de la acogida demasiado cordial de sus anfitriones, desentrañando una trama más siniestra de la que jamás pudo imaginar", "24-02-2017", "Thriller", "Jordan Peele", false, 35, 9, "images/frontMovies/dejamesalir.jpg"),
("Los Cazafantasmas", "Tres parapsicólogos desempleados deciden formar un equipo de eliminación de entidades paranormales en Nueva York, enfrentándose a espectros, fantasmas y demonios, culminando en una batalla contra un dios sumerio en el corazón de la ciudad", "08-06-1984", "Comedy", "Ivan Reitman", false, 30, 7, "images/frontMovies/loscazafantasmas.jpg"),
("Braveheart", "William Wallace, un guerrero escocés, lidera una revuelta contra el tiránico rey inglés Edward I en el siglo XIII", "24-05-1995", "Drama", "Mel Gibson", false, 92, 10, "images/frontMovies/braveheart.jpg"),
("Kill Bill", "Una asesina traicionada por su jefe Bill y sus antiguos compañeros emprende una venganza sin cuartel contra ellos, enfrentándose a varios enemigos en su camino", "10-10-2003", "Thriller", "Quentin Tarantino", false, 71, 12, "images/frontMovies/killbill1.jpg"),
("Kill Bill 2", "La Novia continúa su búsqueda de venganza contra su exjefe y amante Bill, el responsable de su intento de asesinato y el de su hijo no nacido", "16-04-2004", "Thriller", "Quentin Tarantino", true, 72, 12, "images/frontMovies/killbill2.jpg"),
("El laberinto del fauno", "En la España de posguerra, una joven se refugia en un mundo fantástico y aterrador para escapar de la crueldad de su padrastro, un capitán del ejército franquista", "11-10-2006", "Fantasy", "Guillermo del Toro", false, 29, 10, "images/frontMovies/ellaberintodelfauno.jpg"),
("El viaje de Chihiro", "Perdida en un mundo mágico, una niña debe trabajar en un baño de espíritus para liberar a sus padres transformados y regresar al mundo humano", "20-07-2001", "Fantasy", "Hayao Miyazaki", false, 19, 8, "images/frontMovies/elviajedechihiro.jpg"),
("Tigre y Dragón", "En la China de la dinastía Qing, dos maestros de artes marciales se enfrentan a sus últimos desafíos mientras se cruzan con el destino de una espada mágica y el amor prohibido", "08-07-2000", "Drama", "Ang Lee", false, 8, 7, "images/frontMovies/tigreydragon.jpg"),
("American Psycho", "Un joven ejecutivo de Wall Street esconde su psicopatía alternando entre su vida cotidiana como financiero y su oscuro secreto como asesino en serie", "14-04-2000", "Horror", "Mary Harron", true, 23, 9, "images/frontMovies/americanpsycho.jpg"),
("47 Ronin", "Basada en una historia real japonesa, un grupo de samuráis desterrados busca venganza contra el señor que mató a su maestro y los condenó al destierro", "25-12-2013", "Action", "Carl Rinsch", true, 54, 8, "images/frontMovies/47ronin.jpg"),
("Pretty Woman", "Un rico hombre de negocios contrata a una prostituta para varios eventos sociales, pero su relación se profundiza más allá de lo profesional", "23-03-1990", "Romance", "Garry Marshall", false, 67, 9, "images/frontMovies/prettywoman.jpg"),
("Torrente", "Un corrupto y incompetente policía de Madrid, José Luis Torrente, decide hacer justicia por su cuenta y desmantelar una red de drogas. Con métodos poco ortodoxos y la ayuda de un peculiar equipo, Torrente se embarca en una disparatada misión", "13-03-1998", "Comedy", "Santiago Segura", false, 100, 7, "images/frontMovies/torrente.jpg"),
("Amélie", "Amélie, una joven y soñadora camarera en París, decide cambiar las vidas de las personas que la rodean para mejor, mientras lucha con su propia soledad y búsqueda del amor", "25-04-2001", "Romance", "Jean-Pierre Jeunet", false, 55, 8, "images/frontMovies/amelie.jpg"),
("Pearl Harbor", "La vida de dos mejores amigos pilotos de la fuerza aérea se ve interrumpida por el ataque japonés a Pearl Harbor, mientras ambos se enamoran de la misma enfermera", "25-05-2001", "Drama", "Michael Bay", false, 31, 10, "images/frontMovies/pearlharbor.jpg"),
("Dirty Dancing", "Durante el verano de 1963, Frances 'Baby' Houseman se enamora de Johnny Castle, el instructor de baile del resort donde se hospeda con su familia, en un romance que desafía las divisiones sociales y familiares", "21-08-1987", "Romance", "Emile Ardolino", false, 40, 9, "images/frontMovies/dirtydancing.jpg"),
("Armageddon", "Un grupo de perforadores de petróleo es enviado al espacio por la NASA para detener un asteroide gigante en curso de colisión con la Tierra", "01-07-1998", "Action", "Michael Bay", false, 33, 7, "images/frontMovies/armageddon.jpg"),
("Mar adentro", "Basada en la historia real de Ramón Sampedro, quien luchó durante 28 años por el derecho a la eutanasia y su propia muerte digna, tras quedar tetrapléjico en un accidente", "03-09-2004", "Drama", "Alejandro Amenábar", false, 50, 8, "images/frontMovies/maradentro.jpg"),
("El código Da Vinci", "Robert Langdon, un profesor de simbología, se ve envuelto en un misterio asesino vinculado al Vaticano y a una sociedad secreta. Junto a Sophie Neveu, debe descifrar códigos y enfrentarse a enigmas que podrían sacudir los cimientos del cristianismo", "19-05-2006", "Thriller", "Ron Howard", true, 42, 12, "images/frontMovies/elcodigodavinci.jpg"),
("Algo pasa con Mary", "Un hombre se reencuentra con su amor de la secundaria, Mary, años después de una desastrosa cita, solo para descubrir que todavía está enamorado de ella. Sin embargo, no es el único que busca el afecto de Mary", "15-07-1998", "Comedy", "Bobby Farrelly, Peter Farrelly", false, 11, 8, "images/frontMovies/algopasaconmary.jpg"),
("Pulp Fiction", "Las vidas de dos asesinos a sueldo, un boxeador, la esposa de un gánster y un par de bandidos se entrelazan en cuatro historias de violencia y redención", "14-10-1994", "Crime", "Quentin Tarantino", true, 16, 9, "images/frontMovies/pulpfiction.jpg");


-- INSERT EN BBDD TABLA CART_DETAILS
INSERT INTO cart_details (cartid, catalogue_catalogueid, quantity) VALUES
(1, 29, 1),
(1, 1, 3),
(1, 34, 2),
(2, 29, 5);


-- INSERT EN BBDD TABLA inc_new_movies
INSERT INTO inc_new_movies (title, release_date) VALUES
("Capitán América: Brave New World", '2025-02-14'),
("Blancanives", '2025-03-21'),
("Minecraft", '2025-04-04'),
("Michael", '2025-04-18'),
("Misión: Imposible 8", '2025-05-23'),
("Jurassic City", '2025-07-12'),
("Superman", '2025-07-11'),
("Avatar 3", '2025-12-19');